### ISSUE TITLE
Update key identities.

### ISSUE THREAD

**Issue by billynothingelse** [emoose/xvdtool#2]
The previous unknown keys along side their identities are provided as follows:
ODK   = Offline Distribution Key
CIK     = Content Instance Key

**Comment by emoose** [comment]
Hmm, I heard CIK = 'Content Integrity Key' before from some MS PlayReady documentation (this page mentions it: https://msdn.microsoft.com/en-gb/library/ff632564.aspx), so I went with that, but it didn't really make much sense to me since it's used for a lot more than just integrity checking...

Your definitions seem to fit better though.

**Comment by billyhulbert** [comment]
I cannot provide a source without compromising but I can assure that they are correct. More information can be exchanged between us elsewhere if you wish.
