### ISSUE TITLE
Changes to XVC format?

### ISSUE THREAD

**Issue by TronRin** [emoose/xvdtool#36]
![xvc_manifesintheopen](https://user-images.githubusercontent.com/58121124/108324485-40d48700-71c8-11eb-9c3f-9dea17418007.PNG)
So it seems some newer .xvc packages for XBOX games had changes done as far as the format.
As the screenshot shows for the game "Project Winter", the manifest is entirely unencrypted. In fact, if you use certain tools that are able to recover ntfs partition from image file, you can extract everything from the .xvc. That catch is, that of course, aside from the manifest and some other files, everything is still encrypted. I'm curious if it's possible to add support in xvdtool. Namely to jest extract everything even if it's encrypted. Would it be possible? The newer packages have a different file name btw. These always have "_x.xvc" at the end now.

**Comment by tuxuser** [comment]
Closing in favor of issue #39 

Yes, the filenames (filetable) is stored in plaintext, the actual NTFS section that holds the data is encrypted tho.
Extracted the raw, crypted data is of no use, because not each file is encrypted but rather the whole filesystem partion.
It can only be decrypted as whole blocks.
