### ISSUE TITLE
Decrypting XVC using CIK

### ISSUE THREAD

**Issue by moti477** [emoose/xvdtool#59]
Hello,
When I try to decrypt the file I got massage: "Using CIK: 33ec8436-5a0e-4f0d-b1ce-3f29c3955039"
And than I got error : "Decrypting XVC...
                                    Did not find CIK 886a1c1f-47d3-491a-5d6a-61652b8360ab loaded in Keystorage
                                    Checking for XML licenses...
                                    Error during decryption!"
1) How to fix this error?
2) How to find the second CIK key that "loaded in Keystorage"?

**Comment by tuxuser** [comment]
> How to fix this error?

Is it a MSIXVC that you own the license for? If so, use https://github.com/LukeFZ/CikExtractor/tree/master/CikExtractor

then you copy the gathered CIK to the xvdtool's `Cik/` folder and try again.

If it's not, afaik, you cannot acquire the license.

> How to find the second CIK key that "loaded in Keystorage"?

I guess the error message is kind of vague.

It means: This particular key cannot be used, because it was not found.

**Comment by moti477** [comment]
> > How to fix this error?
> 
> Is it a MSIXVC that you own the license for? If so, use https://github.com/LukeFZ/CikExtractor/tree/master/CikExtractor
> 
> then you copy the gathered CIK to the xvdtool's `Cik/` folder and try again.
> 
> If it's not, afaik, you cannot acquire the license.
> 
> > How to find the second CIK key that "loaded in Keystorage"?
> 
> I guess the error message is kind of vague.
> 
> It means: This particular key cannot be used, because it was not found.
Thank you.
