### ISSUE TITLE
Order of loading keys

### ISSUE THREAD

**Issue by tuxuser** [emoose/xvdtool#9]
Planned architecture of loading keyfiles:

Introduce directories to store each type of key.
- OdkKeys/
- CikKeys/
- XvdSignKeys/

1) Load from global directory: _Users/<User>/AppData/xvdtool_ or something like that
2) Load from executable directory
3) Provide cmdline parameters, e.g. `-rsa rsaPrivKey.bin -cik cikKey.bin -odk odkKey.bin`. Parameters on cmdline take precedence of course.

**Comment by emoose** [comment]
Sounds good, the filename of each key can be the KeyID I suppose (GUID for CIKs, int for ODKs), for sign keys I guess the filename can be anything, we just check each file against the known hashes.

Maybe we should allow the format of the file to be both binary and text? If file is {key size} bytes exactly then read it in as binary, otherwise read it as a hex string and convert to binary?

**Comment by tuxuser** [comment]
As previously discussed, loading keys from hexstring is not supported.

Sent PR #10 
It also addresses #6

**Comment by tuxuser** [comment]
Thanks for merging!
